version: "3.5"

services:
  alerts:
    build: .
    command: ["/bin/bash", "-c", "gunicorn -k uvicorn.workers.UvicornWorker shortener.main:app --bind 0.0.0.0:8080 --workers 4 --threads 8"]
    restart: always
    environment:
      REDIS_DSN: redis://localhost:6379
    networks:
      - services_3rd_redis
      - supervisor

networks:
  redis_redis:
    external: true
  supervisor:
    driver: bridge
