name: Build Clients

on:
    push

jobs:
    build-linux:
        runs-on: ubuntu-18.04
        steps:
            - uses: olafurpg/setup-scala@v10
            - uses: actions/checkout@v1
            - name: build project
              run: |
                cd desktop-client
                sbt universal:packageBin
            - name: upload linux artifact
              uses: actions/upload-artifact@v1
              with:
                name: zumba-linux-binary
                path: desktop-client/target/universal/zumba-0.1.zip

    build-windows:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v1
            - uses: olafurpg/setup-scala@v10
            - name: build windows binary
              shell: cmd
              run: "cd desktop-client && sbt windows:packageBin"
            - name: find windows artifact
              run: |
                cd desktop-client/target
                dir
            - name: upload windows artifact
              uses: actions/upload-artifact@v1
              with:
                name: zumba-windows-installer
                path: desktop-client/target/windows/zumba-0.1.msi
